set(_CATKIN_CURRENT_PACKAGE "urdf02_rviz")
set(urdf02_rviz_VERSION "0.0.0")
set(urdf02_rviz_MAINTAINER "jy <jy@todo.todo>")
set(urdf02_rviz_PACKAGE_FORMAT "2")
set(urdf02_rviz_BUILD_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "urdf" "xacro")
set(urdf02_rviz_BUILD_EXPORT_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "urdf" "xacro")
set(urdf02_rviz_BUILDTOOL_DEPENDS "catkin")
set(urdf02_rviz_BUILDTOOL_EXPORT_DEPENDS )
set(urdf02_rviz_EXEC_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "urdf" "xacro")
set(urdf02_rviz_RUN_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "urdf" "xacro")
set(urdf02_rviz_TEST_DEPENDS )
set(urdf02_rviz_DOC_DEPENDS )
set(urdf02_rviz_URL_WEBSITE "")
set(urdf02_rviz_URL_BUGTRACKER "")
set(urdf02_rviz_URL_REPOSITORY "")
set(urdf02_rviz_DEPRECATED "")